version: "3.9"

services:
  mariadb:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - mariadb_joomla_wordpress

  joomla:
    image: joomla
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - "1335:80"
    links:
      - mariadb:mysql
    networks:
      - mariadb_joomla_wordpress
      - default
    environment:
      - JOOMLA_DB_HOST=mariadb:3306
      - JOOMLA_DB_USER=root
      - JOOMLA_DB_NAME="joomla"
      - JOOMLA_DB_PASSWORD=root
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.joomla.entrypoints=http"
      - "traefik.http.routers.joomla.rule=Host(`localhost`) && PathPrefix(`/joomla`)"
      - "traefik.http.routers.joomla.middlewares=joomla-mw@docker"
      - "traefik.http.services.joomla.loadbalancer.server.port=80"
      - "traefik.http.middlewares.joomla-mw.replacepathregex.regex=^/joomla/(.*)"
      - "traefik.http.middlewares.joomla-mw.replacepathregex.replacement=/$$1"

  wordpress:
    image: wordpress
    networks:
      - mariadb_joomla_wordpress
      - default
    ports:
      - "1336:80"
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.wordpress.entrypoints=http"
      - "traefik.http.routers.wordpress.rule=Host(`localhost`) && PathPrefix(`/wordpress`)"
      - "traefik.http.routers.wordpress.middlewares=wordpress-mw@docker"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
      - "traefik.http.middlewares.wordpress-mw.replacepathregex.regex=^/wordpress/(.*)"
      - "traefik.http.middlewares.wordpress-mw.replacepathregex.replacement=/$$1"

  reverse-proxy:
    image: traefik:v2.8
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - mariadb_joomla_wordpress

volumes:
  wordpress:

networks:
  mariadb_joomla_wordpress: {}

