version: "3.1"

services:

  py-backend:
    image: pyencoder-backend:latest
    ports:
      - "8000:8000"
    networks:
      - backend
      - database

  spring-frontend:
    image: pyencoder-frontend:latest
    ports:
      - "80:8080"
    networks:
      - backend
      - web
    depends_on:
      - py-backend

networks:
  web:
    external: true
  backend:
  database: