version: "3.1"

services:

  py-backend:
    image: pyencoder-backend:latest
    ports:
      - "8000:8000"
    networks:
      - backend
      - database
      - default
      - web

networks:
  backend:
  database:
  web:
    external: true