version: '3.1'

services:
    db:
        image: mariadb
        restart: unless-stopped
        environment:
            MARIADB_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        networks:
            - mariadb_joomla_wordpress

networks:
    mariadb_joomla_wordpress: {}
